//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <Dialogs.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>
#include <Grids.hpp>
#include <jpeg.hpp>
#include <ComCtrls.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
        TStatusBar *StatusB;
        TPageControl *PageControl1;
        TTabSheet *TabSheet1;
        TTabSheet *TabSheet2;
        TOpenDialog *OpenDialog_F1;
        TSaveDialog *SaveDialog_F1;
        TPanel *Panel5;
        TLabel *Label156;
        TLabel *Label157;
        TLabel *Label158;
        TLabel *Label159;
        TLabel *Label160;
        TLabel *Label161;
        TLabel *Label162;
        TLabel *Label163;
        TLabel *Label164;
        TLabel *Label165;
        TLabel *Label166;
        TLabel *Label167;
        TLabel *Label168;
        TLabel *Label169;
        TLabel *Label170;
        TLabel *Label171;
        TLabel *Label172;
        TLabel *Label173;
        TLabel *Label174;
        TLabel *Label175;
        TLabel *Label176;
        TLabel *Label177;
        TLabel *Label178;
        TLabel *Label179;
        TLabel *Label180;
        TLabel *Label181;
        TLabel *Label182;
        TLabel *Label183;
        TLabel *Label184;
        TLabel *Label185;
        TLabel *Label186;
        TLabel *Label187;
        TLabel *Label188;
        TLabel *Label189;
        TLabel *Label190;
        TLabel *Label2;
        TLabel *Label3;
        TLabel *Label4;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *Label7;
        TLabel *Label8;
        TLabel *Label9;
        TComboBox *Combo_Vol;
        TEdit *Edit_Vol;
        TEdit *Edit_VDDQ;
        TComboBox *Combo_tCLKAVG;
        TEdit *Edit_nCycleTime_MTB;
        TEdit *Edit_nCycleTime_FTB;
        TComboBox *Combo_tCAS;
        TEdit *Edit_tCAS_MTB;
        TEdit *Edit_tCAS_FTB;
        TComboBox *Combo_tRCD;
        TEdit *Edit_tRCD_MTB;
        TEdit *Edit_tRCD_FTB;
        TComboBox *Combo_tRP;
        TEdit *Edit_tRP_MTB;
        TEdit *Edit_tRP_FTB;
        TComboBox *Combo_tRAS;
        TEdit *Edit_tRAS_MTB;
        TEdit *Edit_tRAS_FTB;
        TComboBox *Combo_tRC;
        TEdit *Edit_tRC_MTB;
        TEdit *Edit_tRC_FTB;
        TEdit *Edit_tRFC;
        TEdit *Edit_tRFC1_LSB;
        TEdit *Edit_tRFC1_MSB;
        TComboBox *Combo_tWR;
        TEdit *Edit_tWR_MTB;
        TEdit *Edit_tWR_FTB;
        TGroupBox *GroupBox3;
        TCheckBox *CheckBox20;
        TCheckBox *CheckBox22;
        TCheckBox *CheckBox24;
        TCheckBox *CheckBox26;
        TCheckBox *CheckBox28;
        TCheckBox *CheckBox30;
        TCheckBox *CheckBox32;
        TCheckBox *CheckBox34;
        TCheckBox *CheckBox50;
        TCheckBox *CheckBox48;
        TCheckBox *CheckBox46;
        TCheckBox *CheckBox44;
        TCheckBox *CheckBox42;
        TCheckBox *CheckBox40;
        TCheckBox *CheckBox38;
        TCheckBox *CheckBox36;
        TCheckBox *CheckBox52;
        TCheckBox *CheckBox54;
        TCheckBox *CheckBox56;
        TCheckBox *CheckBox58;
        TCheckBox *CheckBox60;
        TCheckBox *CheckBox62;
        TCheckBox *CheckBox64;
        TCheckBox *CheckBox66;
        TCheckBox *CheckBox68;
        TCheckBox *CheckBox70;
        TCheckBox *CheckBox72;
        TCheckBox *CheckBox74;
        TCheckBox *CheckBox76;
        TCheckBox *CheckBox78;
        TCheckBox *CheckBox80;
        TCheckBox *CheckBox82;
        TCheckBox *CheckBox84;
        TCheckBox *CheckBox86;
        TCheckBox *CheckBox88;
        TCheckBox *CheckBox90;
        TCheckBox *CheckBox92;
        TCheckBox *CheckBox94;
        TCheckBox *CheckBox96;
        TCheckBox *CheckBox98;
        TEdit *Edit711;
        TEdit *Edit712;
        TEdit *Edit713;
        TEdit *Edit714;
        TButton *Btn_Loadini;
        TButton *Btn_Saveini;
        TEdit *Edit_tRFC2;
        TEdit *Edit_tRFC2_LSB;
        TEdit *Edit_tRFC2_MSB;
        TEdit *Edit_tRFCsb;
        TEdit *Edit_tRFCsb_LSB;
        TEdit *Edit_tRFCsb_MSB;
        TEdit *Edit715;
        TComboBox *Combo_VDDQ;
        TGroupBox *GroupBox1;
        TRadioButton *RadioButton1;
        TRadioButton *RadioButton2;
        TRadioButton *RadioButton3;
        TComboBox *Combo_VPP;
        TEdit *Edit_VPP;
        TPanel *Panel6;
        TLabel *Label191;
        TLabel *Label192;
        TLabel *Label193;
        TLabel *Label194;
        TLabel *Label195;
        TLabel *Label196;
        TLabel *Label197;
        TLabel *Label198;
        TLabel *Label199;
        TLabel *Label200;
        TLabel *Label201;
        TLabel *Label202;
        TLabel *Label203;
        TLabel *Label204;
        TLabel *Label205;
        TLabel *Label206;
        TLabel *Label207;
        TLabel *Label208;
        TLabel *Label209;
        TLabel *Label210;
        TLabel *Label211;
        TLabel *Label212;
        TLabel *Label213;
        TLabel *Label214;
        TLabel *Label215;
        TLabel *Label216;
        TLabel *Label217;
        TLabel *Label218;
        TLabel *Label219;
        TLabel *Label220;
        TLabel *Label221;
        TLabel *Label222;
        TLabel *Lab_Dir;
        TLabel *Label224;
        TLabel *Label225;
        TLabel *Label226;
        TLabel *Label227;
        TLabel *Label228;
        TLabel *Label229;
        TLabel *Label230;
        TLabel *Label231;
        TLabel *Label232;
        TLabel *Label233;
        TLabel *Label234;
        TLabel *Label235;
        TLabel *Label236;
        TLabel *Label237;
        TLabel *Label238;
        TLabel *Label239;
        TStringGrid *StringGrid1;
        TRadioButton *RadioBIN;
        TRadioButton *RadioSPD;
        TButton *Btn_Create2;
        TButton *Btn_Save;
        TImage *Img_mini5;
        TImage *Img_mini4;
        TImage *Img_mini3;
        TImage *Img_mini2;
        TImage *Image_Close_Over;
        TImage *Image_Close_Normal;
        TImage *Image_Close_Down;
        TImage *Img_mini1;
        TLabel *Label100;
        TLabel *Label93;
        TLabel *Label94;
        TLabel *Label95;
        TLabel *Label96;
        TLabel *Label97;
        TLabel *Label98;
        TLabel *Label99;
        TLabel *Label1;
        TImage *Image_Close;
        TLabel *Lb_Close;
        TImage *Img_minimize;
        TLabel *Lb_Mini;
        TLabel *Label10;
        TButton *BitBtn1;
        TButton *BitBtn3;
        TOpenDialog *OpenDialog1;
        TSaveDialog *SaveDialog1;
        TStatusBar *StatusBar1;
        TPanel *Panel1;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label13;
        TLabel *Label14;
        TLabel *Label15;
        TLabel *Label16;
        TLabel *Label17;
        TLabel *Label18;
        TLabel *Label19;
        TLabel *Label20;
        TLabel *Label21;
        TLabel *Label22;
        TLabel *Label23;
        TLabel *Label24;
        TLabel *Label25;
        TLabel *Label26;
        TLabel *Label27;
        TLabel *Label28;
        TLabel *Label29;
        TLabel *Label30;
        TLabel *Label31;
        TLabel *Label32;
        TLabel *Label33;
        TLabel *Label34;
        TLabel *Label35;
        TLabel *Label36;
        TLabel *Label37;
        TLabel *Label38;
        TLabel *Label39;
        TLabel *Label40;
        TLabel *Label41;
        TLabel *Label42;
        TLabel *Label43;
        TLabel *Label44;
        TLabel *Label45;
        TLabel *Label46;
        TLabel *Label47;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label55;
        TLabel *Label56;
        TLabel *Label57;
        TLabel *Label58;
        TLabel *Label59;
        TStringGrid *StringGrid2;
        TStatusBar *StatusBar2;
        TLabel *Lab_XMP1;
        TLabel *Lab_XMP3;
        TLabel *Label60;
        TLabel *Label61;
        TLabel *LMemSpec;
        TLabel *Label62;
        TLabel *Label63;
        TLabel *Label64;
        TCheckBox *EXPOBOX;
        TGroupBox *GroupBox2;
        TRadioButton *RadioButton4;
        TRadioButton *RadioButton5;
        TRadioButton *RadioButton6;
        TRadioButton *RadioButton7;
        TGroupBox *GroupBox4;
        TRadioButton *RadioButton8;
        TRadioButton *RadioButton9;
        TRadioButton *RadioButton10;
        TRadioButton *RadioButton11;
        TCheckBox *CheckBox1;
        TCheckBox *CheckBox2;
        TRadioButton *RadioButton12;
        TRadioButton *RadioButton13;
        TRadioButton *RadioButton14;
        TRadioButton *RadioButton15;
        TCheckBox *CheckBox3;
        TGroupBox *GroupBox5;
        TCheckBox *CheckBox4;
        TLabel *Label65;
        TLabel *Lab_Expo;
        TLabel *Label66;
        TLabel *Lab_Expo2;
        TCheckBox *EXPOBOX2;
        TGroupBox *GroupBox6;
		 void __fastcall StringGrid1DrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
		 void __fastcall FormCreate(TObject *Sender);
		 void __fastcall Btn_SaveClick(TObject *Sender);
		  void __fastcall Lb_MiniMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall Lb_CloseMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall Lb_CloseMouseEnter(TObject *Sender);
    void __fastcall Lb_CloseMouseLeave(TObject *Sender);
    void __fastcall Lb_CloseMouseUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall Lb_MiniMouseEnter(TObject *Sender);
    void __fastcall Lb_MiniMouseLeave(TObject *Sender);
    void __fastcall Lb_MiniMouseUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
    void __fastcall FormMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
	void __fastcall Btn_SaveiniClick(TObject *Sender);
    void __fastcall Btn_LoadiniClick(TObject *Sender);
	void __fastcall Btn_Create2Click(TObject *Sender);
        void __fastcall BitBtn1Click(TObject *Sender);
        void __fastcall BitBtn3Click(TObject *Sender);
        void __fastcall StringGrid1GetEditMask(TObject *Sender, int ACol,
          int ARow, AnsiString &Value);
        void __fastcall StringGrid1KeyPress(TObject *Sender, char &Key);
        void __fastcall StringGrid1SelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
       
        void __fastcall StringGrid2GetEditMask(TObject *Sender, int ACol,
          int ARow, AnsiString &Value);
        void __fastcall StringGrid2KeyPress(TObject *Sender, char &Key);
        void __fastcall StringGrid2SelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
        void __fastcall EXPOBOXClick(TObject *Sender);
        void __fastcall RadioButton3Click(TObject *Sender);
        void __fastcall StringGrid2DrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall RadioButton4Click(TObject *Sender);
        void __fastcall RadioButton5Click(TObject *Sender);
        void __fastcall RadioButton6Click(TObject *Sender);
        void __fastcall RadioButton7Click(TObject *Sender);
        void __fastcall CheckBox1Click(TObject *Sender);
        void __fastcall RadioButton8Click(TObject *Sender);
        void __fastcall RadioButton9Click(TObject *Sender);
        void __fastcall RadioButton11Click(TObject *Sender);
        void __fastcall CheckBox2Click(TObject *Sender);
        void __fastcall RadioButton10Click(TObject *Sender);
        void __fastcall RadioButton12Click(TObject *Sender);
        void __fastcall RadioButton13Click(TObject *Sender);
        void __fastcall RadioButton14Click(TObject *Sender);
        void __fastcall RadioButton15Click(TObject *Sender);
        void __fastcall CheckBox3Click(TObject *Sender);
        void __fastcall CheckBox4Click(TObject *Sender);
        void __fastcall RadioButton1Click(TObject *Sender);
        void __fastcall RadioButton2Click(TObject *Sender);
       
private:	// User declarations
public:		// User declarations
		unsigned short mkcrc16(unsigned short crc16, unsigned char ch);
		char getnibbleL(char x);
    char getnibbleH(char x);
    __fastcall TForm1(TComponent* Owner);
		char TForm1::nibbleX(char x);
    char TForm1::mstrToByte(PUCHAR DataBuffer,int index);
    void NewPrintDataBuffer(PCHAR DataBuffer, ULONG BufferLength);
    void ClearGrid(void);
		void Show_MemSpec(void);
    void Show_XMPSpec(void);
    void Show_EXPO(void);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
